### ISSUE TITLE
Potential issue with uploading a single gzip'ed fastq file made up of a contatenation of gzipped files

### ISSUE THREAD

**Issue by jean-baka** [enasequence/readtools#19]
Hi there, using webin-cli and the Aspera protocol (`-ascp` option), I have validated and uploaded "successfully" some raw reads from ONT MinION, in a single gzipped file obtained for the direct concatenation of 1,000+ reads files. This is legit (see for instance https://stackoverflow.com/questions/8005114/fast-concatenation-of-multiple-gzip-files), and the resulting concatenated file passes the `zcat` test you mention [here](https://ena-docs.readthedocs.io/en/latest/faq/runs.html#fastq-files)  (meaning `zcat`'s return code on it is 0). But the error that was reported to me afterwards by your validating pipeline is:

> webin-cli/reads/AYB_TSs-11_Oxford_Nanopore_cDNA_sequencing_from_leaf_tissue/all-AYB-leaf-cDNA-fastq_pass.gz | Invalid file content | 3a725d4f94a7f4caa117c8cbc500cb6d | 11985658938 | 12-JAN-24 | ERR12448413

I am now trying to go through the slow process of gunzip'ping all the individual files and then re-gzip the whole stream at once, but... This will take time. Where is the problem with my original upload?

**Comment by jean-baka** [comment]
@raskoleinonen ?

**Comment by raskoleinonen** [comment]
We are investigating the issue.

**Comment by raskoleinonen** [comment]
We have a rare false positive read name duplication error coming from a Bloom filter in our validation pipeline. We are working on a fix to overcome this error.

**Comment by jean-baka** [comment]
Thank you @raskoleinonen for the information. I have re-uploaded my problematic files (each one a "clean" file, actually gzipped as a single file from a stream of decompressed individual gzipped files, `gunzip -c *.fastq.gz | gzip -c > reads.gz` kind of commandline) to the Webin FTP server 2 days ago (with same filenames, in same subdirectories) under ERR12448329, ERR12448330 and ERR12448413 (project PRJEB57813). I expect they will be validated automatically from your end once the bug is fixed. If there is any action to perform on my side, please let me know. Thanks again.

**Comment by raskoleinonen** [comment]
We have fixed our duplicated read name detection code; the ERR12448413, ERR12448329 and ERR12448330 have been processed. Thank you for your patience.
